# Generated by Django 3.1.1 on 2020-10-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('author', models.CharField(max_length=200, verbose_name='Author')),
                ('voice', models.CharField(max_length=200, verbose_name='Voice')),
                ('audio_cover_url', models.CharField(blank=True, max_length=300, verbose_name='Audio Cover Url')),
                ('description', models.CharField(max_length=1000, verbose_name='Description')),
                ('audio_url', models.CharField(blank=True, max_length=100, verbose_name='Audio Url')),
            ],
        ),
    ]
